/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/7mqQ0i0pGOM
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Button } from "@/components/ui/button"
import { Textarea } from "@/components/ui/textarea"
import { DropdownMenu, DropdownMenuTrigger, DropdownMenuContent, DropdownMenuLabel, DropdownMenuSeparator, DropdownMenuItem } from "@/components/ui/dropdown-menu"
import { Select, SelectTrigger, SelectValue, SelectIcon, SelectContent, SelectItem } from "@/components/ui/select"

export function Component() {
  return (
    <div className="flex flex-col items-center justify-center h-screen w-full bg-background">
      <div className="max-w-2xl w-full px-4 sm:px-6 lg:px-8">
        <div className="flex flex-col items-center space-y-8">
          <img src="/placeholder.svg" width={200} height={200} alt="Voice AI Assistant" className="rounded-full mt-8" />
          <div className="flex flex-col items-center space-y-4">
            <h1 className="text-4xl font-bold tracking-tight text-foreground sm:text-5xl lg:text-6xl">
              Voice AI Assistant
            </h1>
            <p className="text-xl text-muted-foreground">Interact with our powerful voice AI assistant.</p>
          </div>
          <Button size="lg" className="flex items-center justify-center gap-2 w-full">
            <MicIcon className="h-6 w-6" />
            Start Conversation
          </Button>
          <div className="w-full rounded-md border border-input bg-card p-2">
            <Textarea className="h-20 resize-none" placeholder="Transcribed text will be displayed here..." />
            <Textarea className="h-20 resize-none" placeholder="AI response will be displayed here..." />
          </div>
          <DropdownMenu>
            <DropdownMenuTrigger asChild />
            <DropdownMenuContent align="end" className="w-56">
              <DropdownMenuLabel>Voice Assistant Settings</DropdownMenuLabel>
              <DropdownMenuSeparator />
              <DropdownMenuItem>
                <div className="flex items-center justify-between">
                  <span>Voice</span>
                  <Select>
                    <SelectTrigger className="w-32">
                      <SelectValue placeholder="Select voice" />
                      <div>
                        <ChevronDownIcon className="h-4 w-4" />
                      </div>
                    </SelectTrigger>
                    <SelectContent>
                      <SelectItem value="voice1">Voice 1</SelectItem>
                      <SelectItem value="voice2">Voice 2</SelectItem>
                      <SelectItem value="voice3">Voice 3</SelectItem>
                    </SelectContent>
                  </Select>
                </div>
              </DropdownMenuItem>
              <DropdownMenuItem>
                <div className="flex items-center justify-between">
                  <span>Language</span>
                  <Select>
                    <SelectTrigger className="w-32">
                      <SelectValue placeholder="Select language" />
                      <div>
                        <ChevronDownIcon className="h-4 w-4" />
                      </div>
                    </SelectTrigger>
                    <SelectContent>
                      <SelectItem value="en">English</SelectItem>
                      <SelectItem value="es">Spanish</SelectItem>
                      <SelectItem value="fr">French</SelectItem>
                    </SelectContent>
                  </Select>
                </div>
              </DropdownMenuItem>
              <DropdownMenuItem>
                <div className="flex items-center justify-between">
                  <span>Personality</span>
                  <Select>
                    <SelectTrigger className="w-32">
                      <SelectValue placeholder="Select personality" />
                      <div>
                        <ChevronDownIcon className="h-4 w-4" />
                      </div>
                    </SelectTrigger>
                    <SelectContent>
                      <SelectItem value="friendly">Friendly</SelectItem>
                      <SelectItem value="professional">Professional</SelectItem>
                      <SelectItem value="casual">Casual</SelectItem>
                    </SelectContent>
                  </Select>
                </div>
              </DropdownMenuItem>
            </DropdownMenuContent>
          </DropdownMenu>
        </div>
      </div>
    </div>
  )
}

function ChevronDownIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m6 9 6 6 6-6" />
    </svg>
  )
}


function MicIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M12 2a3 3 0 0 0-3 3v7a3 3 0 0 0 6 0V5a3 3 0 0 0-3-3Z" />
      <path d="M19 10v2a7 7 0 0 1-14 0v-2" />
      <line x1="12" x2="12" y1="19" y2="22" />
    </svg>
  )
}
